language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.4 DB=sqlite
  - DJANGO=1.4 DB=postgres
  - DJANGO=1.4 DB=mysql
  - DJANGO=1.5 DB=sqlite
  - DJANGO=1.5 DB=postgres
  - DJANGO=1.5 DB=mysql
  - DJANGO=1.6 DB=sqlite
  - DJANGO=1.6 DB=postgres
  - DJANGO=1.6 DB=mysql
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.4 DB=sqlite
    - python: "3.2"
      env: DJANGO=1.4 DB=postgres
    - python: "3.2"
      env: DJANGO=1.4 DB=mysql
    - python: "3.3"
      env: DJANGO=1.4 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.4 DB=postgres
    - python: "3.3"
      env: DJANGO=1.4 DB=mysql

    - python: "3.2"
      env: DJANGO=1.5 DB=mysql
    - python: "3.3"
      env: DJANGO=1.5 DB=mysql
    - python: "3.2"
      env: DJANGO=1.6 DB=mysql
    - python: "3.3"
      env: DJANGO=1.6 DB=mysql
before_script:
  - PYFLAKES_NODOCTEST=1 flake8 --max-line-length=100 modeltranslation
  - mysql -e 'create database modeltranslation;'
  - psql -c 'create database modeltranslation;' -U postgres
install:
  - if [[ $DB == mysql ]]; then pip install -q mysql-python --use-mirrors; fi
  - if [[ $DB == postgres ]]; then pip install -q psycopg2 --use-mirrors; fi
  - pip install -q Pillow --use-mirrors
  - pip install -q flake8 --use-mirrors
  - IDJANGO=$(./travis.py $DJANGO)
  - pip install -q $IDJANGO
  - pip install -e . --use-mirrors
script:
  - django-admin.py --version
  - ./runtests.py
